[package]
name = "matrix_mul"
version = "0.1.0"
authors = ["Eric Kunze <eric.kunze@gmx.net>"]

[dependencies]
iron = "*"
persistent = "*"
rustc-serialize = "*"

[dependencies.bodyparser]
git = "https://github.com/iron/body-parser.git"
